[package]
name = "Rays"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
obj = "0.10.2"
ndarray = "0.15.4"
# obj-rs = "0.7.0"

